#!/usr/bin/env ruby

require 'fileutils'

GRADER_ENV = 'grading'
require File.join(File.dirname(__FILE__),'config/environment')

def config
  Grader::Configuration.get_instance
end
RAILS_ENV = config.rails_env
require RAILS_ROOT + '/config/environment'

def extract_submission(user, problem, submission, outdir_name)
  dir = "#{outdir_name}/#{user.login}"
  ext = submission.language.ext
  source_name = "#{problem.name}.#{ext}"
  FileUtils.mkdir_p(dir)
  f = File.open("#{dir}/#{source_name}","w")
  f.write(submission.source)
  f.close
end

def main()
  problem_name = ARGV[0]
  outdir_name = ARGV[1]

  problem = Problem.find_by_name(problem_name)
  User.find_each do |u|
    last_sub = Submission.find_last_by_user_and_problem(u.id, problem.id)
    if last_sub!=nil
      extract_submission(u, problem, last_sub, outdir_name)
    end
  end
end

main
